/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tadesse.bahirehasab.tray;

import java.awt.Graphics;

/**
 *
 * @author user pc
 */
public class IconPanel extends javax.swing.JPanel {

    /**
     * Creates new form IconPanel
     *
     * @param day
     */
    public IconPanel(int day) {
        initComponents();
        this.day.setText(String.format("%d", day));
        setSize(200, 200);
    }

    @Override
    public void paint(Graphics g) {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        day = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(50, 50));

        day.setFont(new java.awt.Font("Monospaced", 0, 72)); // NOI18N
        day.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        day.setText("1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(day, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(day, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel day;
    // End of variables declaration//GEN-END:variables
}
